name: Package or Publish to Marketplace

on:
  workflow_dispatch:
    inputs:
      skip_publish:
        description: 'Skip publishing to the Marketplace'
        required: false
        type: boolean
        default: true

  # push:
  #   branches:
  #     - master
  #   paths:
  #     - "server/**"
  #     - "client/**"
  #     - "package.json"
  pull_request:
    branches:
      - master
    paths:
      - "server/**"
      - "client/**"


env:
  PUBLISHER: LemurDaniel
  PAT: ${{ secrets.PUBLISH_PAT }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
  
      # - name: Install dependencies
      #   run: | 
      #     npm install 
      #     npm rebuild --prefix ./server --platform=win32  --arch=x64   sharp
      #     npm rebuild --prefix ./server --platform=linux  --arch=x64   sharp
      #     npm rebuild --prefix ./server --platform=linux  --arch=arm64 sharp
      #     npm rebuild --prefix ./server --platform=darwin --arch=x64   sharp
      #     npm rebuild --prefix ./server --platform=darwin --arch=arm64 sharp

      - name: Package extension
        if: inputs.skip_publish == true || github.event_name == 'pull_request'
        run: |
          npm install -g @vscode/vsce@3.5.0
          npx vsce package

      - uses: actions/upload-artifact@v4
        if: inputs.skip_publish == true || github.event_name == 'pull_request'
        with:
          name: Upload Extension package
          path: |
            ./*.vsix
          
      - name: Publish extension to Marketplace
        if: inputs.skip_publish == false && github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          npm install -g @vscode/vsce@3.5.0
          npx vsce publish --pat ${{ env.PAT }}
    