name: Node.js CI

on:
  push:
    branches:
     - master
    
env:
  PUBLISHER: LemurDaniel
  TARGET: ./package
  PAT: ${{ secrets.PUBLISH_PAT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
  
      - run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package --out ${{ env.TARGET }}
         
      - name: Publish extension
        run: vsce --pat ${{ env.PAT }} --target ${{ env.TARGET }}
          
    