name: Publish to Marketplace

on:
  workflow_dispatch:
  push:
    branches:
     - fix_sharp_installing_issue
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
  
      - name: Install dependencies
        run: | 
          npm install 
          npm rebuild --prefix ./server --platform=win32  --arch=x64   sharp
          npm rebuild --prefix ./server --platform=linux  --arch=x64   sharp
          npm rebuild --prefix ./server --platform=linux  --arch=arm64 sharp
          npm rebuild --prefix ./server --platform=darwin --arch=x64   sharp
          npm rebuild --prefix ./server --platform=darwin --arch=arm64 sharp

      - name: Package extension
        run: |
          npm install -g vsce
          vsce package

      - uses: actions/upload-artifact@v3
        with:
          name: Upload Package
          path: |
            ./*.vsix
            ./server/node_modules/sharp
          
    