name: Publish to Marketplace

on:
  workflow_dispatch:
  push:
    branches:
     - fix_sharp_installing_issue
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
  
      - name: Install dependencies
        run: | 
          npm install
          npm install --prefix ./server sharp --platform=win32 --arch x64
          npm rebuild --prefix ./server sharp --platform=win32 --arch arm64
          npm rebuild --prefix ./server sharp --platform=darwin --arch x64
          npm rebuild --prefix ./server sharp --platform=darwin --arch arm64
          npm rebuild --prefix ./server sharp --platform=linux --arch x64
          npm rebuild --prefix ./server sharp --platform=linux --arch arm64

      - name: Package extension
        run: |
          npm install -g vsce
          vsce package

      - uses: actions/upload-artifact@v3
        with:
          name: Upload Package
          path: |
            ./*.vsix
            ./server/node_modules/sharp
          
    